'use client';

import { useRef, useState, useEffect, type ReactNode } from 'react';
import Image from 'next/image';
import { motion, useReducedMotion, useInView, animate } from 'framer-motion';
import { ArrowUpRight, ArrowDown, Plus, Minus, Menu, X, Camera as Instagram, Globe2, Sparkles, Target, Code2, Smartphone, PenTool, ArrowRight } from 'lucide-react';

const instagram = 'https://www.instagram.com/brandorbita.global/';
const services = [
  { title: 'Digital Marketing', icon: Globe2, description: 'The big picture. The right channels. A strategy that connects your brand with the people who matter — and turns attention into action.', tags: ['Digital strategy', 'SEO & content', 'Growth planning'] },
  { title: 'Social Media Management', icon: Sparkles, description: 'Build a presence people recognise and a community that keeps coming back. From content calendars to creative and conversations, we connect every post to a purpose.', tags: ['Content creation', 'Community', 'Social strategy'] },
  { title: 'Website Design & Development', icon: Code2, description: 'Your most powerful first impression. We create distinctive, responsive websites that pair thoughtful design with fast performance and a clear path to conversion.', tags: ['UI / UX design', 'Development', 'E-commerce'] },
  { title: 'Google Ads & Paid Media', icon: Target, description: 'Reach people with intent. We bring creative, audience insight and ongoing optimisation together to make every advertising decision more informed.', tags: ['Google Ads', 'Meta Ads', 'Conversion tracking'] },
  { title: 'App Development', icon: Smartphone, description: 'Turn a useful idea into an intuitive product. We design and develop mobile experiences around real user needs, from the first prototype to launch.', tags: ['Product design', 'Mobile apps', 'Prototyping'] },
  { title: 'Branding & Creative', icon: PenTool, description: 'A brand with its own gravitational pull. Distinctive identities, compelling stories and creative systems that stay consistent wherever you show up.', tags: ['Brand identity', 'Art direction', 'Visual systems'] },
];
function Reveal({children, className = ''}: {children: ReactNode; className?: string}) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : {opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,ease:[.22,1,.36,1]}}>{children}</motion.div>; }
function Button({children, href, secondary = false}: {children:ReactNode;href:string;secondary?:boolean}) { const ref=useRef<HTMLAnchorElement>(null); return <a ref={ref} href={href} className={`button ${secondary?'secondary':''}`} onPointerMove={e=>{if(e.pointerType==='mouse' && !window.matchMedia('(prefers-reduced-motion: reduce)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`;}}} onPointerLeave={e=>{e.currentTarget.style.transform='';}}>{children}<ArrowUpRight size={17}/></a>; }
function Orbital({small=false}:{small?:boolean}) { return <div className={`orbital ${small?'small':''}`} aria-hidden="true"><div className="orbital-halo"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="planet"><div className="planet-grid"/><div className="planet-shine"/></div><div className="orbit orbit-front"/><div className="orbit orbit-blue"/><div className="orbit-dot"/><span className="space-coordinate coordinate-one">23° 26′ / LIMITLESS POTENTIAL</span><span className="space-coordinate coordinate-two">BRAND ORBITA · GLOBAL</span></div>; }
function Counter({value,suffix,label}:{value:number;suffix:string;label:string}) {const ref=useRef<HTMLSpanElement>(null);const visible=useInView(ref,{once:true});const reduced=useReducedMotion();useEffect(()=>{if(visible){if(reduced){if(ref.current)ref.current.textContent=String(value);return;} const controls=animate(0,value,{duration:1.5,onUpdate:v=>{if(ref.current)ref.current.textContent=String(Math.round(v));}});return()=>controls.stop();}},[visible,value,reduced]);return <div className="stat"><strong><span ref={ref}>{value}</span>{suffix}</strong><span>{label}</span></div>;}

export default function Agency(){const [menu,setMenu]=useState(false);const [active,setActive]=useState(2);const [filter,setFilter]=useState('All work');
return <><a href="#main" className="skip-link">Skip to content</a><header className="header"><a href="#" aria-label="Brand Orbita Global home" className="brand"><Image src="/brandorbita.png" alt="Brand Orbita" width={1536} height={1024} priority/><span>GLOBAL</span></a><nav aria-label="Main navigation" className={menu?'nav open':'nav'}>{[['About','#about'],['Services','#services'],['Our work','#work'],['Our process','#process']].map(([label,url])=><a key={url} href={url} onClick={()=>setMenu(false)}>{label}</a>)}<a className="mobile-contact" href="#contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={16}/></a></nav><a href="#contact" className="nav-cta">Let’s talk <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main id="main"><section className="hero"><div className="stars" aria-hidden="true"/><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> INDEPENDENT THINKING. GLOBAL AMBITION.</div><h1>Your brand.<br/><span>In orbit.</span><span className="headline-star" aria-hidden="true">✦</span></h1><p>We blend bold strategy, exceptional design and<br className="desktop-break"/> digital intelligence to take your brand further.</p><div className="hero-actions"><Button href="#contact">Launch your next chapter</Button><a className="text-link" href="#work">Explore our work <ArrowUpRight size={17}/></a></div><div className="hero-note"><span className="tiny-orbit">◎</span> BUILT TO STAND OUT. DESIGNED TO GO FURTHER.</div></div><div className="hero-art"><Orbital/></div><div className="hero-bottom"><a href="#about"><span className="scroll-circle"><ArrowDown size={15}/></span> SCROLL TO EXPLORE</a><span>STRATEGY × CREATIVITY × TECHNOLOGY</span><span className="hero-index">01 — 09</span></div></section>
<div className="discipline-strip" aria-label="Our disciplines">{['STRATEGY','DESIGN','DEVELOPMENT','DIGITAL GROWTH','BRAND EXPERIENCES'].map(x=><span key={x}>{x}<i>✦</i></span>)}</div>
<section id="about" className="section about"><Reveal><div className="eyebrow muted">01 / THE AGENCY</div><h2>Great brands don’t<br/>stand still.<br/><span className="serif gold">Neither do we.</span></h2></Reveal><Reveal className="about-copy"><span className="mini-cross">✦</span><p className="large-copy">We’re Brand Orbita Global.<br/>Your creative force for what’s next.</p><p>We bring strategy, creativity and technology into one orbit. From your first impression to your next stage of growth, we build digital experiences that make your brand impossible to overlook.</p><a className="text-link gold" href="#services">A world of possibilities <ArrowUpRight size={18}/></a></Reveal></section>
<section id="services" className="section services"><Reveal className="section-heading"><div><div className="eyebrow muted">02 / OUR EXPERTISE</div><h2>One partner.<br/><span className="serif">Infinite possibilities.</span></h2></div><p>Everything your brand needs to<br/>move in the right direction.</p></Reveal><div className="services-layout"><Reveal className="service-visual"><span className="eyebrow">CONNECTED BY DESIGN</span><div className="service-orb">✦<div/><div/></div><div><span className="service-number">0{active+1} / 06</span><h3>{services[active].title}</h3><span className="muted">Your next move, made meaningful.</span></div></Reveal><div className="accordion">{services.map((s,i)=><div className={`service ${active===i?'active':''}`} key={s.title}><h3><button aria-expanded={active===i} aria-controls={`service-${i}`} onClick={()=>setActive(i)}><span className="row-number">0{i+1}</span><span>{s.title}</span>{active===i?<Minus size={19}/>:<Plus size={19}/>}</button></h3><div id={`service-${i}`} hidden={active!==i} className="service-details"><p>{s.description}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div><a href="#contact" className="text-link">Let’s explore <ArrowUpRight size={16}/></a></div></div>)}</div></div></section>
<section id="work" className="section work"><Reveal className="section-heading"><div><div className="eyebrow muted">03 / CREATIVE EXPLORATIONS</div><h2>Different worlds.<br/><span className="serif">Same ambition.</span></h2></div><p>A glimpse of what we can imagine.<br/>Self-initiated concepts, built to inspire.</p></Reveal><div className="filters" aria-label="Filter projects">{['All work','Web design','Branding','Digital marketing'].map(f=><button aria-pressed={filter===f} className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{(filter==='All work'||filter==='Web design')&&<Reveal className="project project-large"><a href="#contact" className="project-art atelier" aria-label="Discuss an editorial e-commerce website"><div className="mock-browser"><div className="mock-nav"><b>FORMA</b><span>Objects for considered living. ↗</span></div><div className="forma-body"><span>LESS, BUT<br/><em>better.</em></span><div className="sculpture">f.</div></div><div className="mock-bottom">THE EVERYDAY, ELEVATED <span>EXPLORE THE COLLECTION ↗</span></div></div><span className="project-open"><ArrowUpRight/></span></a><div className="project-caption"><div><h3>Forma — Considered living</h3><p>Web design & development · E-commerce concept</p></div><span>01</span></div></Reveal>}{(filter==='All work'||filter==='Branding')&&<Reveal className="project"><a href="#contact" className="project-art novas" aria-label="Discuss a brand identity project"><span className="concept-kicker">A DIFFERENT KIND OF ENERGY.</span><strong>nóva<span>®</span></strong><span className="nova-line"/><div className="concept-bottom">FIND YOUR FREQUENCY.<span>BRAND CONCEPT / 2026</span></div><span className="project-open"><ArrowUpRight/></span></a><div className="project-caption"><div><h3>Nóva — A new frequency</h3><p>Brand strategy · Visual identity concept</p></div><span>02</span></div></Reveal>}{(filter==='All work'||filter==='Digital marketing')&&<Reveal className="project campaign"><a href="#contact" className="project-art pulse" aria-label="Discuss a digital marketing campaign"><div className="pulse-label">OFFLINE IS<br/><em>the new luxury.</em></div><span className="pulse-tag">UNPLUG. GO FURTHER.</span><div className="campaign-caption">ROAM / CAMPAIGN EXPLORATION <ArrowUpRight/></div><span className="project-open"><ArrowUpRight/></span></a><div className="project-caption"><div><h3>Roam — Beyond the everyday</h3><p>Digital marketing · Campaign concept</p></div><span>03</span></div></Reveal>}</div></section>
<section id="process" className="section process"><Reveal className="section-heading"><div><div className="eyebrow muted">04 / THE WAY WE WORK</div><h2>Big thinking.<br/><span className="serif">Precisely executed.</span></h2></div><p>No disconnected services. No guesswork.<br/>One team, aligned with your ambition.</p></Reveal><div className="process-grid">{[{name:'Discover',text:'We get curious. About your business, your audience and the opportunity ahead.'},{name:'Define',text:'We set the direction. A clear strategy, shared priorities and a plan with purpose.'},{name:'Create',text:'We make it real. Distinctive creative and considered technology, crafted together.'},{name:'Elevate',text:'We launch, learn and refine. Because moving forward is an ongoing process.'}].map((p,i)=><Reveal key={p.name}><span className="step-num">0{i+1}<ArrowRight size={18}/></span><h3>{p.name}<span>.</span></h3><p>{p.text}</p></Reveal>)}</div><Reveal className="stats"><Counter value={6} suffix="" label="Connected disciplines"/><Counter value={4} suffix="" label="Steps from idea to impact"/><Counter value={1} suffix="" label="Team around your brand"/><div className="stat"><strong>∞</strong><span>Possibilities ahead</span></div></Reveal></section>
<section id="social" className="section social"><Reveal className="section-heading"><div><div className="eyebrow muted">05 / INSIDE OUR ORBIT</div><h2>Stay a little <span className="serif">closer.</span></h2></div><a href={instagram} target="_blank" rel="noopener noreferrer" className="text-link"><Instagram size={19}/> @brandorbita.global <ArrowUpRight size={17}/></a></Reveal><div className="social-grid"><a href={instagram} target="_blank" rel="noopener noreferrer" className="social-tile social-brand"><Image src="/brandorbita.png" alt="Brand Orbita gold and blue orbital identity" width={1536} height={1024}/><span>OUR UNIVERSE <Instagram size={17}/></span></a><a href={instagram} target="_blank" rel="noopener noreferrer" className="social-tile social-type"><span>THINK BIGGER.</span><strong>Make<br/>some<br/><em>gravity.</em></strong><span>CREATIVE THINKING <Instagram size={17}/></span></a><a href={instagram} target="_blank" rel="noopener noreferrer" className="social-tile social-blue"><div className="social-symbol">✳</div><span>IDEAS IN MOTION <Instagram size={17}/></span></a></div><p className="social-note">Brand explorations from our studio. Follow our Instagram for the latest.</p></section>
<section id="contact" className="contact"><Reveal><div className="eyebrow"><span className="status-dot"/> YOUR NEXT CHAPTER STARTS HERE</div><h2>Ready for a<br/><span className="serif gold">new trajectory?</span></h2><p>Tell us where you want to go.<br/>Let’s build the way there, together.</p><Button href={instagram}>Let’s talk on Instagram</Button><span className="contact-hint">Send us a DM at @brandorbita.global</span></Reveal><div className="contact-ring" aria-hidden="true"/></section></main>
<footer className="footer"><div className="footer-top"><div><a href="#" className="brand footer-brand" aria-label="Brand Orbita Global home"><Image src="/brandorbita.png" alt="Brand Orbita" width={1536} height={1024}/><span>GLOBAL</span></a><p>Independent minds. Shared ambition.<br/>Your brand, in orbit.</p></div><div className="footer-links"><span>EXPLORE</span><a href="#about">The agency</a><a href="#services">Our expertise</a><a href="#work">Our work</a></div><div className="footer-links"><span>CONNECT</span><a href={instagram} target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="#contact">Start a conversation <ArrowUpRight size={14}/></a><span className="footer-location">Thinking globally. Creating together.</span></div><a href="#" className="back-top" aria-label="Back to top"><ArrowUpRight size={22}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Brand Orbita Global. All rights reserved.</span><span>CRAFTED WITH INTENT. BUILT FOR IMPACT. <span className="gold">✦</span></span></div></footer></>;
}


